# Generated by Django 5.1.5 on 2025-02-13 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_user_id_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_interval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repetition_period',
            field=models.CharField(blank=True, choices=[('Fun', 'Fun'), ('Work', 'Work'), ('School', 'School'), ('Chore', 'Chore'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_interval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='A very important task.')),
                ('type', models.CharField(choices=[('Fun', 'Fun'), ('Work', 'Work'), ('School', 'School'), ('Chore', 'Chore'), ('Other', 'Other')], default='Other', max_length=20)),
                ('urgency', models.IntegerField(default=3)),
                ('repetition_period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tasks.recurringpattern'),
        ),
    ]
