# Generated by Django 5.1.6 on 2025-02-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_recurringpattern_type_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpattern',
            name='name',
            field=models.CharField(default='Untitled Recurring Task', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Untitled Task', max_length=200),
        ),
    ]
