# Generated by Django 5.1.5 on 2025-02-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_end_interval_task_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_interval',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='task',
            name='repetition_period',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_interval',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('Fun', 'Fun'), ('Work', 'Work'), ('School', 'School'), ('Chore', 'Chore'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
