# Generated by Django 5.1.5 on 2025-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_recurringpattern_type_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpattern',
            name='type',
            field=models.CharField(choices=[('Fun', 'Fun'), ('Work', 'Work'), ('School', 'School'), ('Chore', 'Chore'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('Fun', 'Fun'), ('Work', 'Work'), ('School', 'School'), ('Chore', 'Chore'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
